name: Deploy Backend to Render

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'server/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Run tests
        working-directory: ./server
        run: |
          go mod download
          go test ./...
          
      - name: Build application
        working-directory: ./server
        run: |
          go mod tidy
          go build -o app ./cmd/shrimpy
          
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
            
      - name: Verify deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
        run: |
          echo "Backend deployment initiated successfully!"
          echo "Monitor deployment at: https://dashboard.render.com/web/$RENDER_SERVICE_ID"
